In [26]:
import torch

In [4]:
words = open("names.txt", 'r').read().splitlines()

In [6]:
len(words)

32033

In [109]:
N = torch.zeros((27,27), dtype=torch.int32)

In [110]:
char = sorted(set("".join(words)))
itos = {i+1:s for i,s in enumerate(char)}
itos[0] = '.'
stoi = {s:i for i,s in itos.items()}

In [111]:
for w in words:
    w = '.' + w + '.'
    for ch1,ch2 in zip(w,w[1:]):
        ix1 = stoi[ch1] ; ix2 = stoi[ch2]
        N[ix1,ix2] += 1

In [121]:
P = N.float()
P = P / P.sum(1, keepdim=True)
P.sum(1)

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000])

In [122]:
g = torch.Generator().manual_seed(5565458552)

In [123]:
for _ in range(20):
    ix = 0
    p = []
    while True:
        ix = torch.multinomial(P[ix],num_samples=1,replacement=True,generator=g).item()
        p.append(itos[ix])
        if ix == 0:
            break
    print("".join(p))

tifrieimo.
jumarosorad.
ayve.
kaa.
eodextotzlenahvinn.
frreyn.
a.
kan.
jayrlaxxx.
a.
goxa.
jashakauintramyzar.
maeyabre.
as.
diedldiu.
anaglendr.
aro.
jone.
lan.
vi.


In [88]:
N[ix]

tensor([0.0000, 0.1377, 0.0408, 0.0481, 0.0528, 0.0478, 0.0130, 0.0209, 0.0273,
        0.0184, 0.0756, 0.0925, 0.0491, 0.0792, 0.0358, 0.0123, 0.0161, 0.0029,
        0.0512, 0.0642, 0.0408, 0.0024, 0.0117, 0.0096, 0.0042, 0.0167, 0.0290])

In [115]:
a = torch.tensor([[1,1,1,1],
                  [2,3,3,3],
                  [1,2,5,6]])
a

tensor([[1, 1, 1, 1],
        [2, 3, 3, 3],
        [1, 2, 5, 6]])

In [120]:
a.sum(1,keepdim=True)

tensor([[ 4],
        [11],
        [14]])